### ISSUE TITLE
File I/O Error

### ISSUE THREAD

**Issue by IronCityCoder** [IronCityCoder/glass#1]
```
Traceback (most recent call last):
  File "../../glass.py", line 139, in <module>
    processDirectories(directory)
  File "../../glass.py", line 53, in processDirectories
    ftype = m.from_file(os.path.abspath(fname))
File "/usr/local/lib/python3.6/dist-packages/magic.py", line 86, in from_file
    with open(filename):
FileNotFoundError: [Errno 2] No such file or directory: '/.../Apple iPhone (...)/.../https_www.glassdoor.com_0.localstorage-wal'
```

Magic is having issues parsing the absolute path to the filename. This could be caused for several reasons, such as the parenthesis or spaces in the path, but it could also think that the file is **"https_www\.glassdoor"** and then the rest of the actual filename is ignored, preventing it from being opened. 

Tomorrow I'll test removing the `os.path.abspath` to verify that the error persists. If it does, a solution that I have in mind would be having a function to handle paths and run that through Magic. For instance, we create a temporary copy of the file with a usable name (like "001") and pass that file into the function call. 

It's late but I am also writing a reminder here to check Magic's Issues page to see if there are known file parsing issues.

**Comment by IronCityCoder** [comment]
Or pass in a backslash before periods.

**Comment by IronCityCoder** [comment]
Pulled new code from GitHub and ran it and got errors with broken links instead. Passed in some error handling for that and everything runs fine. 

Made a test file with Magic and ran this specific file's path and it opened. Will attempt one more runthrough then close this issue and push the new code.

**Comment by IronCityCoder** [comment]
Turns out os.walk itself has some problems when handling named pipes.

`default.realm.note: fifo (named pipe)` is inside the directory where it gets stuck. Will swap libraries from os to [pathlib](https://docs.python.org/3.7/library/pathlib.html)

**Comment by IronCityCoder** [comment]
Successfully moved over to pathlib and no longer require python-magic! Closed!
